version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=MMZ.settings
    command: python /app/manage.py runserver 0.0.0.0:8000